# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cb5003d6a0fc96400f85c44edcafdec0c260d98449f4147a9dd3deb67226bc2795d1eb247d84e456dd9971a37a23d1caf0161d076798423a305c3297373692a

test:
  secret_key_base: 7e530d7dbc2142fefb63a2ae1173bcf652d2938a98dfcede702c9c1518f3f880ebaae93d9b255f957e873273bf5d7b23f8b895f031f6b516f8ebdf182c6444ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
